const goods = [
	{
		id: 1,
		title: 'пончо, размер М/Л',
		discription: 'Ручная вышивка, эко-кожа, замша',
		previewDiscription: 'Ручная вышивка, эко-кожа, замша',
		sale: true,
		sliderImg: '/img/collections/1/preview-img/1.jpg',
		altText:'пончо',
		urlToFullInformation: "/ru/collections/1/",
		collection: 2021,
		gridStyleTamplate: 'template-galery_1',
		galeryImages: [
			{link: '/img/collections/1/1.jpg', altText: 'product photo'},
			{link: '/img/collections/1/2.jpg', altText: 'product photo'},
			{link: '/img/collections/1/3.jpg', altText: 'product photo'},
			{link: '/img/collections/1/4.jpg', altText: 'product photo'},
			{link: '/img/collections/1/5.jpg', altText: 'product photo'},
			{link: '/img/collections/1/6.jpg', altText: 'product photo'},
		],
	},
	{
		id:  2,
		title: 'юбка',
		discription: 'Ручная вышивка, эко-кожа с подкладкой из сетки',
		previewDiscription: 'Ручная вышивка, эко-кожа',
		sale: true,
		sliderImg: '/img/collections/2/preview-img/1.jpg',
		altText:'юбка',
		urlToFullInformation: "/ru/collections/2/",
		collection: 2021,
		gridStyleTamplate: 'template-galery_2',
		galeryImages: [
			{link: '/img/collections/2/1.jpg', altText: 'product photo'},
			{link: '/img/collections/2/2.jpg', altText: 'product photo'},
			{link: '/img/collections/2/3.jpg', altText: 'product photo'},
			{link: '/img/collections/2/4.jpg', altText: 'product photo'},
			{link: '/img/collections/2/5.jpg', altText: 'product photo'},
			{link: '/img/collections/2/6.jpg', altText: 'product photo'},
			{link: '/img/collections/2/7.jpg', altText: 'product photo'},
			{link: '/img/collections/2/8.jpg', altText: 'product photo'},
		],
	},
	{
		id:  3,
		title: 'худи, размер L',
		discription: 'Ручная вышивка, хлопок',
		previewDiscription: 'Ручная вышивка, хлопок',
		sale: true,
		sliderImg: '/img/collections/3/preview-img/1.jpg',
		altText:'худи',
		urlToFullInformation: "/ru/collections/3/",
		collection: 2021,
		gridStyleTamplate: 'template-galery_3',
		galeryImages: [
			{link: '/img/collections/3/1.jpg', altText: 'product photo'},
			{link: '/img/collections/3/2.jpg', altText: 'product photo'},
			{link: '/img/collections/3/3.jpg', altText: 'product photo'},
			{link: '/img/collections/3/4.jpg', altText: 'product photo'},
			{link: '/img/collections/3/5.jpg', altText: 'product photo'},
		],
	},
	{
		id:  4,
		title: 'футболка, размер М',
		discription: 'Ручная вышивка, вискоза, хлопок',
		previewDiscription:'Ручная вышивка, вискоза, хлопок',
		sale: false,
		sliderImg: '/img/collections/4/preview-img/1.jpg',
		altText:'футболка',
		urlToFullInformation: "/ru/collections/4/",
		collection: 2021,
		gridStyleTamplate: 'template-galery_4',
		galeryImages: [
			{link: '/img/collections/4/1.jpg', altText: 'product photo'},
			{link: '/img/collections/4/2.jpg', altText: 'product photo'},
			{link: '/img/collections/4/3.jpg', altText: 'product photo'},
			{link: '/img/collections/4/4.jpg', altText: 'product photo'},
			{link: '/img/collections/4/5.jpg', altText: 'product photo'},
			{link: '/img/collections/4/6.jpg', altText: 'product photo'},
		],
	},
	{
		id:  5,
		title: 'худи, размер М',
		discription: 'Ручная вышивка, кашемир, вискоза',
		previewDiscription:'Ручная вышивка, кашемир, вискоза',
		sale: false,
		sliderImg: '/img/collections/5/preview-img/1.jpg',
		altText:'худи',
		urlToFullInformation: "/ru/collections/5/",
		collection: 2021,
		gridStyleTamplate: 'template-galery_5',
		galeryImages: [
			{link: '/img/collections/5/1.jpg', altText: 'product photo'},
			{link: '/img/collections/5/2.jpg', altText: 'product photo'},
			{link: '/img/collections/5/3.jpg', altText: 'product photo'},
			{link: '/img/collections/5/4.jpg', altText: 'product photo'},
			{link: '/img/collections/5/5.jpg', altText: 'product photo'},
			{link: '/img/collections/5/6.jpg', altText: 'product photo'},
		],
	},
	{
		id:  6,
		title: 'худи, размер М',
		discription: 'Ручная вышивка, хлопок',
		previewDiscription: 'Ручная вышивка, хлопок',
		sale: false,
		sliderImg: '/img/collections/6/preview-img/1.jpg',
		altText:'худи',
		urlToFullInformation: "/ru/collections/6/",
		collection: 2021,
		gridStyleTamplate: 'template-galery_6',
		galeryImages: [
			{link: '/img/collections/6/1.jpg', altText: 'product photo'},
			{link: '/img/collections/6/2.jpg', altText: 'product photo'},
			{link: '/img/collections/6/3.jpg', altText: 'product photo'},
			{link: '/img/collections/6/4.jpg', altText: 'product photo'},
			{link: '/img/collections/6/5.jpg', altText: 'product photo'},
			{link: '/img/collections/6/6.jpg', altText: 'product photo'},
		],
	},
	{
		id:  7,
		title: 'футболка, размер М',
		discription: 'Ручная вышивка, вискоза, хлопок',
		previewDiscription: 'Ручная вышивка, вискоза, хлопок', 
		sale: false,
		sliderImg: '/img/collections/7/preview-img/1.jpg',
		altText:'футболка',
		urlToFullInformation: "/ru/collections/7/",
		collection: 2021,
		gridStyleTamplate: 'template-galery_7',
		galeryImages: [
			{link: '/img/collections/7/1.jpg', altText: 'product photo'},
			{link: '/img/collections/7/2.jpg', altText: 'product photo'},
			{link: '/img/collections/7/3.jpg', altText: 'product photo'},
			{link: '/img/collections/7/4.jpg', altText: 'product photo'},
			{link: '/img/collections/7/5.jpg', altText: 'product photo'},
			{link: '/img/collections/7/6.jpg', altText: 'product photo'},
		],
	},
	{
		id:  8,
		title: 'футболка, размер М',
		discription: 'Ручная вышивка, хлопок',
		previewDiscription: 'Ручная вышивка, хлопок',  
		sale: false,
		sliderImg: '/img/collections/8/preview-img/1.jpg',
		altText:'футболка',
		urlToFullInformation: "/ru/collections/8/",
		collection: 2021,
		gridStyleTamplate: 'template-galery_8',
		galeryImages: [
			{link: '/img/collections/8/1.jpg', altText: 'product photo'},
			{link: '/img/collections/8/2.jpg', altText: 'product photo'},
			{link: '/img/collections/8/3.jpg', altText: 'product photo'},
			{link: '/img/collections/8/4.jpg', altText: 'product photo'},
			{link: '/img/collections/8/5.jpg', altText: 'product photo'},
		],
	},
	{
		id:  9,
		title: 'футболка, размер М',
		discription: 'Ручная вышивка, хлопок',
		previewDiscription: 'Ручная вышивка, хлопок',  
		sale: false,
		sliderImg: '/img/collections/9/preview-img/1.jpg',
		altText:'футболка',
		urlToFullInformation: "/ru/collections/9/",
		collection: 2021,
		gridStyleTamplate: 'template-galery_9',
		galeryImages: [
			{link: '/img/collections/9/1.jpg', altText: 'product photo'},
			{link: '/img/collections/9/2.jpg', altText: 'product photo'},
			{link: '/img/collections/9/3.jpg', altText: 'product photo'},
			{link: '/img/collections/9/4.jpg', altText: 'product photo'},
		],
	},
	{
		id:  10,
		title: 'бомбер, размер М',
		discription: 'Ручная вышивка',
		previewDiscription: 'Ручная вышивка',  
		sale: false,
		sliderImg: '/img/collections/10/preview-img/1.jpg',
		altText:'бомбер',
		urlToFullInformation: "/ru/collections/10/",
		collection: 2021,
		gridStyleTamplate: 'template-galery_10',
		galeryImages: [
			{link: '/img/collections/10/1.jpg', altText: 'product photo'},
			{link: '/img/collections/10/2.jpg', altText: 'product photo'},
			{link: '/img/collections/10/3.jpg', altText: 'product photo'},
			{link: '/img/collections/10/4.jpg', altText: 'product photo'},
		],
	},
	{
		id:  11,
		title: 'футболка, размер М',
		discription: 'Ручная вышивка, хлопок',
		previewDiscription: 'Ручная вышивка, хлопок',
		sale: false,
		sliderImg: '/img/collections/11/preview-img/1.jpg',
		altText:'нет в продаже',
		urlToFullInformation: "/ru/collections/11/",
		collection: 2021,
		gridStyleTamplate: 'template-galery_11',
		galeryImages: [
			{link: '/img/collections/11/1.jpg', altText: 'product photo'},
			{link: '/img/collections/11/2.jpg', altText: 'product photo'},
			{link: '/img/collections/11/3.jpg', altText: 'product photo'},
			{link: '/img/collections/11/4.jpg', altText: 'product photo'},
		],
	},
]