const goods = [
	{
		//ru
		title: 'пончо, размер М/Л',
		discription: 'Ручная вышивка, эко-кожа, замша',
		previewDiscription: 'Ручная вышивка, эко-кожа, замша',
		altText:'пончо, размер М/Л',
		urlToFullInformation: '/ru/collections/1/',
		//en
		titleEn: 'poncho, one size M/L',
		discriptionEn: 'Embroidery, eco-lather, suede',
		previewDiscriptionEn: 'Embroidery, eco-lather, suede',
		altTextEn:'poncho',
		urlToFullInformationEn: '/en/collections/1/',
		//common
		id: 1,
		sale: true,
		sliderImg: '/img/collections/1/preview-img/1.jpg',
		collection: 2021,
		gridStyleTamplate: 'template-galery_1',
		galeryImages: [
			{link: '/img/collections/1/1.jpg', altText: 'product photo'},
			{link: '/img/collections/1/2.jpg', altText: 'product photo'},
			{link: '/img/collections/1/3.jpg', altText: 'product photo'},
			{link: '/img/collections/1/4.jpg', altText: 'product photo'},
			{link: '/img/collections/1/5.jpg', altText: 'product photo'},
			{link: '/img/collections/1/6.jpg', altText: 'product photo'},
		],
	},
	{
		//ru
		title: 'юбка',
		discription: 'Ручная вышивка, эко-кожа с подкладкой из сетки',
		previewDiscription: 'Ручная вышивка, эко-кожа',
		altText:'юбка',
		urlToFullInformation: '/ru/collections/2/',
		//en
		titleEn: 'skirt',
		discriptionEn: 'Embroidery, eco-lather',
		previewDiscriptionEn: 'Embroidery, eco-lather',
		altTextEn:'skirt',
		urlToFullInformationEn: '/en/collections/2/',
		//common
		id:  2,
		sale: true,
		sliderImg: '/img/collections/2/preview-img/1.jpg',
		collection: 2021,
		gridStyleTamplate: 'template-galery_2',
		galeryImages: [
			{link: '/img/collections/2/1.jpg', altText: 'product photo'},
			{link: '/img/collections/2/2.jpg', altText: 'product photo'},
			{link: '/img/collections/2/3.jpg', altText: 'product photo'},
			{link: '/img/collections/2/4.jpg', altText: 'product photo'},
			{link: '/img/collections/2/5.jpg', altText: 'product photo'},
			{link: '/img/collections/2/6.jpg', altText: 'product photo'},
			{link: '/img/collections/2/7.jpg', altText: 'product photo'},
			{link: '/img/collections/2/8.jpg', altText: 'product photo'},
		],
	},
	{
		//ru
		title: 'худи, размер L',
		discription: 'Ручная вышивка, хлопок',
		previewDiscription: 'Ручная вышивка, хлопок',
		altText:'худи, размер L',
		urlToFullInformation: '/ru/collections/3/',
		//en
		titleEn: 'hoody, one size L',
		discriptionEn: 'Embroidery, cotton',
		previewDiscriptionEn: 'Embroidery, cotton',
		altTextEn:'hoody',
		urlToFullInformationEn: '/en/collections/3/',
		//common
		id:  3,
		sale: true,
		sliderImg: '/img/collections/3/preview-img/1.jpg',
		collection: 2021,
		gridStyleTamplate: 'template-galery_3',
		galeryImages: [
			{link: '/img/collections/3/1.jpg', altText: 'product photo'},
			{link: '/img/collections/3/2.jpg', altText: 'product photo'},
			{link: '/img/collections/3/3.jpg', altText: 'product photo'},
			{link: '/img/collections/3/4.jpg', altText: 'product photo'},
			{link: '/img/collections/3/5.jpg', altText: 'product photo'},
		],
	},
	{
		//ru
		title: 'футболка, размер М',
		discription: 'Ручная вышивка, вискоза, хлопок',
		previewDiscription:'Ручная вышивка, вискоза, хлопок',
		altText:'футболка, размер М',
		urlToFullInformation: '/ru/collections/4/',
		//en
		titleEn: 't-shirt, one size M',
		discriptionEn: 'Embroidery, cotton, viscose',
		previewDiscriptionEn: 'Embroidery, cotton, viscose',
		altTextEn:'t-shirt',
		urlToFullInformationEn: '/en/collections/4/',
		//common
		id:  4,
		sale: false,
		sliderImg: '/img/collections/4/preview-img/1.jpg',
		collection: 2021,
		gridStyleTamplate: 'template-galery_4',
		galeryImages: [
			{link: '/img/collections/4/1.jpg', altText: 'product photo'},
			{link: '/img/collections/4/2.jpg', altText: 'product photo'},
			{link: '/img/collections/4/3.jpg', altText: 'product photo'},
			{link: '/img/collections/4/4.jpg', altText: 'product photo'},
			{link: '/img/collections/4/5.jpg', altText: 'product photo'},
			{link: '/img/collections/4/6.jpg', altText: 'product photo'},
		],
	},
	{
		//ru
		title: 'худи, размер М',
		discription: 'Ручная вышивка, кашемир, вискоза',
		previewDiscription:'Ручная вышивка, кашемир, вискоза',
		altText:'худи, размер М',
		urlToFullInformation: '/ru/collections/5/',
		//en
		titleEn: 'hoody, one size M',
		discriptionEn: 'Embroidery, cashemere, viscose',
		previewDiscriptionEn: 'Embroidery, cashemere, viscose',
		altTextEn:'hoody',
		urlToFullInformationEn: '/en/collections/5/',
		//common
		id:  5,
		sale: false,
		sliderImg: '/img/collections/5/preview-img/1.jpg',
		collection: 2021,
		gridStyleTamplate: 'template-galery_5',
		galeryImages: [
			{link: '/img/collections/5/1.jpg', altText: 'product photo'},
			{link: '/img/collections/5/2.jpg', altText: 'product photo'},
			{link: '/img/collections/5/3.jpg', altText: 'product photo'},
			{link: '/img/collections/5/4.jpg', altText: 'product photo'},
			{link: '/img/collections/5/5.jpg', altText: 'product photo'},
			{link: '/img/collections/5/6.jpg', altText: 'product photo'},
		],
	},
	{
		//ru
		title: 'худи, размер М',
		discription: 'Ручная вышивка, хлопок',
		previewDiscription: 'Ручная вышивка, хлопок',
		altText:'худи, размер М',
		urlToFullInformation: '/ru/collections/6/',
		//en
		titleEn: 'hoody, one size M',
		discriptionEn: 'Embroidery, cotton',
		previewDiscriptionEn: 'Embroidery, cotton',
		altTextEn:'hoody',
		urlToFullInformationEn: '/en/collections/6/',
		//common
		id:  6,
		sale: false,
		sliderImg: '/img/collections/6/preview-img/1.jpg',
		collection: 2021,
		gridStyleTamplate: 'template-galery_6',
		galeryImages: [
			{link: '/img/collections/6/1.jpg', altText: 'product photo'},
			{link: '/img/collections/6/2.jpg', altText: 'product photo'},
			{link: '/img/collections/6/3.jpg', altText: 'product photo'},
			{link: '/img/collections/6/4.jpg', altText: 'product photo'},
			{link: '/img/collections/6/5.jpg', altText: 'product photo'},
			{link: '/img/collections/6/6.jpg', altText: 'product photo'},
		],
	},
	{
		//ru
		title: 'футболка, размер М',
		discription: 'Ручная вышивка, вискоза, хлопок',
		previewDiscription: 'Ручная вышивка, вискоза, хлопок', 
		altText:'футболка, размер М',
		urlToFullInformation: '/ru/collections/7/',
		//en
		titleEn: 't-shirt, one size M',
		discriptionEn: 'Embroidery, cotton, viscose',
		previewDiscriptionEn: 'Embroidery, cotton, viscose',
		altTextEn:'t-shirt',
		urlToFullInformationEn: '/en/collections/7/',
		//common
		id:  7,
		sale: false,
		sliderImg: '/img/collections/7/preview-img/1.jpg',
		collection: 2021,
		gridStyleTamplate: 'template-galery_7',
		galeryImages: [
			{link: '/img/collections/7/1.jpg', altText: 'product photo'},
			{link: '/img/collections/7/2.jpg', altText: 'product photo'},
			{link: '/img/collections/7/3.jpg', altText: 'product photo'},
			{link: '/img/collections/7/4.jpg', altText: 'product photo'},
			{link: '/img/collections/7/5.jpg', altText: 'product photo'},
			{link: '/img/collections/7/6.jpg', altText: 'product photo'},
		],
	},
	{
		//ru
		title: 'футболка, размер М',
		discription: 'Ручная вышивка, хлопок <br>по мотивам картины Рокуела Кента',
		previewDiscription: 'Ручная вышивка, хлопок',  
		altText:'футболка, размер М',
		urlToFullInformation: '/ru/collections/8/',
		//en
		titleEn: 't-shirt, one size M',
		discriptionEn: 'Embroidery, cotton<br> Inspired by Rockwell Kent',
		previewDiscriptionEn: 'Embroidery, cotton',
		altTextEn:'t-shirt',
		urlToFullInformationEn: '/en/collections/8/',
		//common
		id:  8,
		sale: false,
		sliderImg: '/img/collections/8/preview-img/1.jpg',
		collection: 2021,
		gridStyleTamplate: 'template-galery_8',
		galeryImages: [
			{link: '/img/collections/8/1.jpg', altText: 'product photo'},
			{link: '/img/collections/8/2.jpg', altText: 'product photo'},
			{link: '/img/collections/8/3.jpg', altText: 'product photo'},
			{link: '/img/collections/8/4.jpg', altText: 'product photo'},
			{link: '/img/collections/8/5.jpg', altText: 'product photo'},
		],
	},
	{
		//ru
		title: 'футболка, размер М',
		discription: 'Ручная вышивка, хлопок',
		previewDiscription: 'Ручная вышивка, хлопок', 
		altText:'футболка, размер М',
		urlToFullInformation: '/ru/collections/9/',
		//en
		titleEn: 't-shirt, one size M',
		discriptionEn: 'Embroidery, acrylic paint, cotton',
		previewDiscriptionEn: 'Embroidery, acrylic paint, cotton',
		altTextEn:'t-shirt',
		urlToFullInformationEn: '/en/collections/9/',
		//common
		id:  9,
		sale: false,
		sliderImg: '/img/collections/9/preview-img/1.jpg',
		collection: 2021,
		gridStyleTamplate: 'template-galery_9',
		galeryImages: [
			{link: '/img/collections/9/1.jpg', altText: 'product photo'},
			{link: '/img/collections/9/2.jpg', altText: 'product photo'},
			{link: '/img/collections/9/3.jpg', altText: 'product photo'},
			{link: '/img/collections/9/4.jpg', altText: 'product photo'},
		],
	},
	{
		title: 'бомбер, размер М',
		discription: 'Ручная вышивка',
		previewDiscription: 'Ручная вышивка', 
		altText:'бомбер, размер М',
		urlToFullInformation: '/ru/collections/10/',
		//en
		titleEn: 'bomber',
		discriptionEn: 'Embroidery, cotton',
		previewDiscriptionEn: 'Embroidery, cotton',
		altTextEn:'bomber',
		urlToFullInformationEn: '/en/collections/10/',
		//common
		id:  10,
		sale: false,
		sliderImg: '/img/collections/10/preview-img/1.jpg',
		collection: 2021,
		gridStyleTamplate: 'template-galery_10',
		galeryImages: [
			{link: '/img/collections/10/1.jpg', altText: 'product photo'},
			{link: '/img/collections/10/2.jpg', altText: 'product photo'},
			{link: '/img/collections/10/3.jpg', altText: 'product photo'},
			{link: '/img/collections/10/4.jpg', altText: 'product photo'},
		],
	},
	{
		title: 'футболка, размер М',
		discription: 'Ручная вышивка, хлопок',
		previewDiscription: 'Ручная вышивка, хлопок',
		altText:'футболка, размер М',
		urlToFullInformation: '/ru/collections/11/',
		//en
		titleEn: 't-shirt, one size M',
		discriptionEn: 'Embroidery, cotton',
		previewDiscriptionEn: 'Embroidery, cotton',
		altTextEn:'t-shirt',
		urlToFullInformationEn: '/en/collections/11/',
		//common
		id:  11,
		sale: false,
		sliderImg: '/img/collections/11/preview-img/1.jpg',
		collection: 2021,
		gridStyleTamplate: 'template-galery_11',
		galeryImages: [
			{link: '/img/collections/11/1.jpg', altText: 'product photo'},
			{link: '/img/collections/11/2.jpg', altText: 'product photo'},
			{link: '/img/collections/11/3.jpg', altText: 'product photo'},
			{link: '/img/collections/11/4.jpg', altText: 'product photo'},
		],
	},
    {// ==================COLLECTION 2022================================
        id: 12,
		title: 'футболка и бомбер, размер L',
		discription: 'Ручная вышивка, роспись акрилом',
		previewDiscription: 'ручная вышивка, роспись акрилом',
		altText:'футболка и бомбер, размер L',
		urlToFullInformation: `/ru/collections/12/`,
		//en
		titleEn: 't-shirt & bomber, one size L',
		discriptionEn: 'Embroidery, acrylic paint ',
		previewDiscriptionEn: 'Embroidery',
		altTextEn:'t-shirt & bomber, one size L',
		urlToFullInformationEn: `/en/collections/12/`,
		//common	
		sale: false,
		sliderImg: '/img/collections/12/preview-img/1.jpg',
		collection: 2022,
		gridStyleTamplate: 'template-galery_6',
		galeryImages: [
			{link: '/img/collections/12/1.jpg', altText: 'product photo'},
			{link: '/img/collections/12/2.jpg', altText: 'product photo'},
			{link: '/img/collections/12/3.jpg', altText: 'product photo'},
			{link: '/img/collections/12/4.jpg', altText: 'product photo'},
            {link: '/img/collections/12/5.jpg', altText: 'product photo'},
            {link: '/img/collections/12/6.jpg', altText: 'product photo'},
		],
	},
    {
		title: 'кимоно-пальто, размер М',
		discription: 'ручная вышивка',
		previewDiscription: 'ручная вышивка',
		altText:'кимоно-пальто, размер М',
		urlToFullInformation: '/ru/collections/13/',
		//en
		titleEn: 'coat-kimono',
		discriptionEn: 'Embroidery ',
		previewDiscriptionEn: 'Embroidery',
		altTextEn:'coat-kimono ',
		urlToFullInformationEn: '/en/collections/13/',
		//common
		id:  13,
		sale: false,
		sliderImg: '/img/collections/13/preview-img/1.jpg',
		collection: 2022,
		gridStyleTamplate: 'template-galery_3',
		galeryImages: [
			{link: '/img/collections/13/1.jpg', altText: 'product photo'},
			{link: '/img/collections/13/2.jpg', altText: 'product photo'},
			{link: '/img/collections/13/3.jpg', altText: 'product photo'},
			{link: '/img/collections/13/4.jpg', altText: 'product photo'},
            {link: '/img/collections/13/5.jpg', altText: 'product photo'},
		],
	},
    {
		title: 'пончо, размер М/L',
		discription: 'ручная вышивка, искусственная кожа, замша',
		previewDiscription: 'Ручная вышивка, искусственная кожа',
		altText:'нет в продаже',
		urlToFullInformation: '/ru/collections/14/',
		//en
		titleEn: 'poncho, one size M/L',
		discriptionEn: 'Embroidery, eco-lather, suede',
		previewDiscriptionEn: 'Embroidery, eco-lather, suede ',
		altTextEn:'t-shirt',
		urlToFullInformationEn: '/en/collections/14/',
		//common
		id:  14,
		sale: false,
		sliderImg: '/img/collections/14/preview-img/1.jpg',
		collection: 2022,
		gridStyleTamplate: 'template-galery_8',
		galeryImages: [
			{link: '/img/collections/14/1.jpg', altText: 'product photo'},
			{link: '/img/collections/14/2.jpg', altText: 'product photo'},
			{link: '/img/collections/14/3.jpg', altText: 'product photo'},
			{link: '/img/collections/14/4.jpg', altText: 'product photo'},
            {link: '/img/collections/14/5.jpg', altText: 'product photo'},
		],
	},
    {
		title: 'футболка, размер L',
		discription: 'ручная вышивка, хлопок',
		previewDiscription: 'ручная вышивка, хлопок',
		altText:'футболка, размер L',
		urlToFullInformation: '/ru/collections/15/',
		//en
		titleEn: 't-shirt, one size L',
		discriptionEn: 'Embroidery, cotton',
		previewDiscriptionEn: 'Embroidery, cotton',
		altTextEn:'t-shirt, one size L   ',
		urlToFullInformationEn: '/en/collections/15/',
		//common
		id:  15,
		sale: false,
		sliderImg: '/img/collections/15/preview-img/1.jpg',
		collection: 2022,
		gridStyleTamplate: 'template-galery_11',
		galeryImages: [
			{link: '/img/collections/15/1.jpg', altText: 'product photo'},
			{link: '/img/collections/15/2.jpg', altText: 'product photo'},
			{link: '/img/collections/15/3.jpg', altText: 'product photo'},
			{link: '/img/collections/15/4.jpg', altText: 'product photo'},
		],
	},
    {
		title: 'худи, размер М',
		discription: 'ручная вышивка, кашемир',
		previewDiscription: 'Ручная вышивка',
		altText:'худи, размер М',
		urlToFullInformation: '/ru/collections/16/',
		//en
		titleEn: 'hoody, one size M',
		discriptionEn: 'Embroidery, cashmere, eco-leather',
		previewDiscriptionEn: 'Embroidery, cashmere, eco-leather',
		altTextEn:'hoody, one size M',
		urlToFullInformationEn: '/en/collections/16/',
		//common
		id:  16,
		sale: false,
		sliderImg: '/img/collections/16/preview-img/1.jpg',
		collection: 2022,
		gridStyleTamplate: 'template-galery_9',
		galeryImages: [
			{link: '/img/collections/16/1.jpg', altText: 'product photo'},
			{link: '/img/collections/16/2.jpg', altText: 'product photo'},
			{link: '/img/collections/16/3.jpg', altText: 'product photo'},
			{link: '/img/collections/16/4.jpg', altText: 'product photo'},
		],
	},
    {
		title: 'худи, размер М',
		discription: 'ручная вышивка, кашемир',
		previewDiscription: 'ручная вышивка',
		altText:'худи, размер М',
		urlToFullInformation: '/ru/collections/17/',
		//en
		titleEn: 'hoody, one size M',
		discriptionEn: 'Embroidery, cashmere, eco-leather', 
		previewDiscriptionEn: 'Embroidery, cashmere, eco-leather',
		altTextEn:'hoody, one size M',
		urlToFullInformationEn: '/en/collections/17/',
		//common
		id:  17,
		sale: false,
		sliderImg: '/img/collections/17/preview-img/1.jpg',
		collection: 2022,
		gridStyleTamplate: 'template-galery_9',
		galeryImages: [
			{link: '/img/collections/17/1.jpg', altText: 'product photo'},
			{link: '/img/collections/17/2.jpg', altText: 'product photo'},
			{link: '/img/collections/17/3.jpg', altText: 'product photo'},
			{link: '/img/collections/17/4.jpg', altText: 'product photo'},
		],
	},
]